usb: dwc3: updates for multiport controller
ACK is pulling the patchset proposed upstream in [1] for android13-5.15
branch. This patch makes the corresponding modifications per updates to
'struct dwc3'. Since we only have a single port controller here, we can
just always reference the first phy entry.

This fixes several build errors of the following type:
  private/google-modules/soc/gs/drivers/usb/dwc3/dwc3-exynos-otg.c:340:25: \
    error: member reference base type 'struct phy *' is not a structure or union
                        dwc->usb2_generic_phy->power_count = 1;
                        ~~~~~~~~~~~~~~~~~~~~~^ ~~~~~~~~~~~

[1] https://lore.kernel.org/linux-usb/1654709787-23686-4-git-send-email-quic_harshq@quicinc.com/

Bug: 235866160
Tested: P21 module probes fine
Signed-off-by: Carlos Llamas <cmllamas@google.com>
Change-Id: Id760fe1c8127296070dd60daf028b98ceada824f