soc/google/cpif: add missing linux/sched/clock.h include
This had included linux/sched/clock.h (for cpu_clock()) by accident

This included above header (for cpu_clock()) by accident via
linux/skbuff.h which itself was cleaned up for the 6.3-rc1
kernel and we get compilation failures like
    .../kernel.mainline/common/../private/google-modules/soc/gs/drivers/soc/google/cpif/modem_utils.c:140:9: error: call to undeclared function 'cpu_clock'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            time = cpu_clock(this_cpu);
                   ^
See https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2870c4d6a5e4
and https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9ac849f2c492

Bug: 273298779
Test: build and boot
Change-Id: I64e4bea4c140abf7d6847e9b1a18bf1fa53b0a37
Signed-off-by: André Draszik <draszik@google.com>